// Copyright The PDP-Connect Contributors
// SPDX-License-Identifier: Apache-2.0

/**
 * Checked-in exact allowlist for the package-wide `lint/performance/noAwaitInLoops`
 * policy.
 *
 * Two-layer design. biome.jsonc deliberately keeps `noAwaitInLoops: "off"`
 * for `src/`, `bin/`, `bench/`, `connectors/` (its own comment explains why:
 * the package's dominant loop shapes are genuinely sequential) — that
 * override is NOT removed by this file and stays in effect for ordinary
 * `pnpm check`/`biome check` runs. This file is the independent second
 * layer: the sole sanctioned exception mechanism, checked by a dedicated
 * gate that re-enables the rule out-of-band. Every (path, line, column)
 * below is a specific, reviewed, genuinely intentional sequential await,
 * not an escape hatch.
 *
 * Enforcement: `scripts/check-no-await-in-loops-conformance.ts` (wired into
 * `pnpm verify` as `check:noAwaitInLoops-conformance`) re-runs Biome with
 * the rule forced back to "error" for its own invocation only and fails
 * the build on:
 *   1. any LIVE finding whose location is not listed here (a new sequential
 *      await was introduced and was never reviewed/categorized), and
 *   2. any LISTED row whose location Biome no longer flags (the code moved or
 *      changed shape — the exception is stale and must be re-reviewed, not
 *      silently carried forward).
 *
 * Every row is categorized by WHY it must stay sequential — never a generic
 * blanket rationale:
 *
 *   - ordered_browser_interaction: sequential Playwright action against the shared page/context
 *   - dependent_pagination: next request depends on the prior page's cursor/offset/response
 *   - bounded_retry_polling: retry/backoff/poll loop gated on the prior attempt's outcome
 *   - provider_pacing_backpressure: rate-limited/budget-gated external call
 *   - ordered_protocol_emission: Collection Profile protocol emission requiring in-order delivery
 *   - dependent_file_cursor: sequential file/dir walk, incremental byte-offset read, or one-way fs mutation
 *   - shared_mutable_accumulator: loop body mutates a shared accumulator the next iteration reads
 *   - test_assertion_sequencing: test drives/asserts an ordered per-case side effect
 *   - devtool_sequential_output: manual dev-tool script printing ordered per-item console output
 *
 * To add a new entry after a genuine, reviewed addition: run
 *   pnpm exec biome check --only=performance/noAwaitInLoops --max-diagnostics=1000 \
 *     --reporter=json . (with the rule flipped to "error" in a scratch biome.jsonc
 *   copy, or use scripts/check-no-await-in-loops-conformance.ts --dump-live to print
 *   the current live finding set) — then classify ONLY the new row(s) into the
 *   right category above and append them here. Do not regenerate the whole file.
 */

export type NoAwaitInLoopsReasonCategory =
	| "ordered_browser_interaction"
	| "dependent_pagination"
	| "bounded_retry_polling"
	| "provider_pacing_backpressure"
	| "ordered_protocol_emission"
	| "dependent_file_cursor"
	| "shared_mutable_accumulator"
	| "test_assertion_sequencing"
	| "devtool_sequential_output";

export interface NoAwaitInLoopsAllowlistEntry {
	readonly category: NoAwaitInLoopsReasonCategory;
	readonly column: number;
	readonly line: number;
	/** Short, site-specific note — the awaited call this row covers. */
	readonly note: string;
	readonly path: string;
}

export const NO_AWAIT_IN_LOOPS_ALLOWLIST: readonly NoAwaitInLoopsAllowlistEntry[] =
	[
		{
			path: "bench/claude-code-two-pass.ts",
			line: 239,
			column: 13,
			category: "devtool_sequential_output",
			note: "runLegacyBaseline(): manual dev-tool script printing ordered per-item console output",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 306,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 422,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 546,
			column: 10,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 627,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 708,
			column: 3,
			category: "dependent_file_cursor",
			note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 742,
			column: 3,
			category: "dependent_file_cursor",
			note: "processJsonlFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 781,
			column: 3,
			category: "dependent_file_cursor",
			note: "processSessionDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bench/legacy/claude-code-pre-tranche-c.ts",
			line: 822,
			column: 3,
			category: "dependent_file_cursor",
			note: "scanProjectDir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/amazon-privacy-probe.ts",
			line: 42,
			column: 4,
			category: "ordered_browser_interaction",
			note: "page.goto(): sequential Playwright action against the shared page/context",
		},
		{
			path: "bin/register-all.ts",
			line: 77,
			column: 4,
			category: "devtool_sequential_output",
			note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
		},
		{
			path: "bin/replay-pilot-fixtures.ts",
			line: 162,
			column: 13,
			category: "dependent_pagination",
			note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "bin/replay-schemas.ts",
			line: 263,
			column: 18,
			category: "dependent_pagination",
			note: "replayConnector(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 62,
			column: 17,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 172,
			column: 17,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 182,
			column: 16,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "bin/scrub-fixtures.ts",
			line: 189,
			column: 4,
			category: "dependent_file_cursor",
			note: "mkdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 957,
			column: 18,
			category: "dependent_pagination",
			note: "recoverPendingOrderItemDetailGapPage(): resolveOrderDetail(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 968,
			column: 5,
			category: "ordered_protocol_emission",
			note: "recoverPendingOrderItemDetailGapPage(): deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1013,
			column: 18,
			category: "dependent_pagination",
			note: "recoverPendingOrderItemDetailGaps(): recoverPendingOrderItemDetailGapPage(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1233,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitOrderAndItems(): deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1318,
			column: 4,
			category: "ordered_protocol_emission",
			note: "extractAndShapeCheckOrders(): emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 1923,
			column: 5,
			category: "dependent_pagination",
			note: "runYear(): deps.progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 2175,
			column: 6,
			category: "dependent_pagination",
			note: "collect(): progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/index.ts",
			line: 2232,
			column: 6,
			category: "dependent_pagination",
			note: "collect(): progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/amazon/integration.test.ts",
			line: 455,
			column: 19,
			category: "test_assertion_sequencing",
			note: "processListOrder(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/apple_contacts/bounded-response-read.ts",
			line: 93,
			column: 28,
			category: "dependent_file_cursor",
			note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/apple_contacts/carddav-client.ts",
			line: 90,
			column: 39,
			category: "dependent_pagination",
			note: "davRequest(): next redirect hop depends on the prior response's Location header",
		},
		{
			path: "connectors/apple_contacts/carddav-client.ts",
			line: 426,
			column: 15,
			category: "provider_pacing_backpressure",
			note: "addressbookMultiget(): sequential bounded chunks so one change set cannot issue an unbounded parallel fan-out at the provider",
		},
		{
			path: "connectors/apple_contacts/discovery.ts",
			line: 271,
			column: 15,
			category: "dependent_pagination",
			note: "propfindFollowingRedirects(): next redirect hop depends on the prior response's Location header",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 462,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 528,
			column: 4,
			category: "ordered_protocol_emission",
			note: "hydrateMissingBodies(): emitContactRecord() Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 766,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 790,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 813,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitContactRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_contacts/index.ts",
			line: 1022,
			column: 9,
			category: "shared_mutable_accumulator",
			note: "collectAddressBook(): loop body mutates a shared bookCursor/newState accumulator the next iteration reads",
		},
		{
			path: "connectors/apple_health/index.ts",
			line: 77,
			column: 5,
			category: "ordered_protocol_emission",
			note: "onRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/apple_photos/index.ts",
			line: 188,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 1624,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 1825,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 1879,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2012,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): statement DETAIL_GAP emissions preserve source outcome order",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2106,
			column: 3,
			category: "ordered_protocol_emission",
			note: "recoverServedStatementGaps(): deps.emit() per-statement DETAIL_GAP_RECOVERED, Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2633,
			column: 3,
			category: "ordered_protocol_emission",
			note: "recoverServedAccountGaps(): deps.emit() per-account DETAIL_GAP_RECOVERED, Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2665,
			column: 19,
			category: "ordered_browser_interaction",
			note: "processAccountDownload(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/chase/index.ts",
			line: 2985,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 1327,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2147,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2423,
			column: 3,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2707,
			column: 15,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2730,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2826,
			column: 4,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2861,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 2964,
			column: 4,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 3297,
			column: 16,
			category: "provider_pacing_backpressure",
			note: "fetchChatGptPressureProbeStatus(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4028,
			column: 15,
			category: "provider_pacing_backpressure",
			note: "fetchBatch(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4064,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4101,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4130,
			column: 6,
			category: "ordered_protocol_emission",
			note: "emitConversationDetailGapOnce(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4353,
			column: 12,
			category: "provider_pacing_backpressure",
			note: "fetchConversationDetailWaitingOutCircuit(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4443,
			column: 12,
			category: "dependent_pagination",
			note: "deps.api.fetch(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4616,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "recoverPendingConversationDetailGapPage(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 4771,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/index.ts",
			line: 5004,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitConversation(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/chatgpt/integration.test.ts",
			line: 5119,
			column: 3,
			category: "test_assertion_sequencing",
			note: "runConversationsAndMessagesStreams(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 430,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 558,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 598,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 818,
			column: 10,
			category: "dependent_file_cursor",
			note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 924,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 981,
			column: 10,
			category: "dependent_file_cursor",
			note: "readBoundedUtf8(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1082,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "processJsonlFile(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1114,
			column: 4,
			category: "shared_mutable_accumulator",
			note: "processJsonlFile(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1171,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "processSessionDir(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1212,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "scanProjectDir(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1426,
			column: 4,
			category: "ordered_protocol_emission",
			note: "input.reportStreamFailure(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1554,
			column: 14,
			category: "dependent_file_cursor",
			note: "readdir(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1737,
			column: 4,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1809,
			column: 3,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1900,
			column: 3,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1919,
			column: 4,
			category: "ordered_protocol_emission",
			note: "input.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 1949,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitGatedInventoryStream(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 2328,
			column: 18,
			category: "shared_mutable_accumulator",
			note: "scanSessionSource(): loop body mutates a shared accumulator (sessionAccumulators) the next iteration reads",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 2366,
			column: 24,
			category: "shared_mutable_accumulator",
			note: "scanSessionSource(): loop body mutates a shared accumulator (sessionAccumulators) the next iteration reads",
		},
		{
			path: "connectors/claude_code/index.ts",
			line: 2466,
			column: 18,
			category: "shared_mutable_accumulator",
			note: "scanChildSource(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/claude_code/integration.test.ts",
			line: 88,
			column: 3,
			category: "test_assertion_sequencing",
			note: "processJsonlLine(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/claude_code/local-jsonl-incremental.test.ts",
			line: 522,
			column: 5,
			category: "test_assertion_sequencing",
			note: "import(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/claude_code/local-jsonl-incremental.test.ts",
			line: 1098,
			column: 18,
			category: "test_assertion_sequencing",
			note: "makeAttachmentSource(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/codex/index.ts",
			line: 594,
			column: 18,
			category: "dependent_file_cursor",
			note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/codex/index.ts",
			line: 610,
			column: 4,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 629,
			column: 18,
			category: "dependent_file_cursor",
			note: "statAndRead(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/codex/index.ts",
			line: 689,
			column: 9,
			category: "dependent_file_cursor",
			note: "isDirectoryPath(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/codex/index.ts",
			line: 1634,
			column: 31,
			category: "shared_mutable_accumulator",
			note: "scanRollouts(): sequential (not Promise.all) existence check over args.roots — a short, fixed list (today: the primary and archive roots) pushed into a single shared rootChecks accumulator; also keeps the codex file clear of the local-source-bounded-file-read.test.ts .all()-pattern guard, which flags Promise.all as a false positive on the SQLite-unbounded-read pattern it actually polices.",
		},
		{
			path: "connectors/codex/index.ts",
			line: 1667,
			column: 4,
			category: "shared_mutable_accumulator",
			note: "scanRollouts(): the merged sessions/ + sessions-archive/ root walk shares seenCursorKeysThisScan, newFileCursors, newMtimes, and running counters across both roots' walks (see ARCHIVAL-CONTRACT.md); processRolloutEntry mutates them, so the two roots cannot be walked in parallel without a data race on that shared state.",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2180,
			column: 3,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2239,
			column: 4,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2302,
			column: 19,
			category: "ordered_protocol_emission",
			note: "resolveGatedInventoryRecords(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/index.ts",
			line: 2419,
			column: 3,
			category: "ordered_protocol_emission",
			note: "waitForEmitDrain(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/codex/rollout-stream.test.ts",
			line: 255,
			column: 4,
			category: "test_assertion_sequencing",
			note: "once(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/github/index.ts",
			line: 474,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 504,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 598,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 626,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 713,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 745,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 1014,
			column: 16,
			category: "ordered_protocol_emission",
			note: "emitPullRequestItem(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 1054,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 1157,
			column: 18,
			category: "dependent_pagination",
			note: "drainPrSearchWindow(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/github/index.ts",
			line: 1279,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/github/index.ts",
			line: 1302,
			column: 3,
			category: "dependent_pagination",
			note: "guardGithubPagination(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 863,
			column: 21,
			category: "ordered_protocol_emission",
			note: "deps.hydrateAttachment(): canonical field bytes must bind before their record is emitted",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 888,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 912,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 991,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.uploadBodyBlob(): canonical field bytes must bind before their record is emitted",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 1130,
			column: 22,
			category: "ordered_protocol_emission",
			note: "processMessage(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 1455,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 2627,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitProtocol(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 2858,
			column: 16,
			category: "provider_pacing_backpressure",
			note: "processServedAttachmentRecoveryGap(): rate-limited/budget-gated external call",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 3909,
			column: 23,
			category: "dependent_pagination",
			note: "fetchBodiesFn(): sequential IMAP command on a connection that is not concurrent",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 4015,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/gmail/index.ts",
			line: 4264,
			column: 23,
			category: "dependent_pagination",
			note: "runThreadsPass(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/gmail/integration.test.ts",
			line: 2655,
			column: 13,
			category: "test_assertion_sequencing",
			note: "run(): each run feeds the prior run's committed cursor into the next; the walk is the assertion",
		},
		{
			path: "connectors/google_calendar/api.ts",
			line: 226,
			column: 26,
			category: "dependent_pagination",
			note: "listCalendars(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 199,
			column: 6,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 356,
			column: 5,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_calendar/index.ts",
			line: 382,
			column: 3,
			category: "ordered_protocol_emission",
			note: "ctx.progress(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_contacts/api.ts",
			line: 303,
			column: 26,
			category: "dependent_pagination",
			note: "listContactGroups(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_contacts/index.ts",
			line: 248,
			column: 6,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_contacts/index.ts",
			line: 364,
			column: 5,
			category: "ordered_protocol_emission",
			note: "ctx.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_maps/archive-stream.test.ts",
			line: 200,
			column: 4,
			category: "dependent_file_cursor",
			note: "large-path oracle writes one ordered JSON array to a shared stream",
		},
		{
			path: "connectors/google_maps/archive-stream.ts",
			line: 793,
			column: 4,
			category: "ordered_protocol_emission",
			note: "drain(): sequential event callbacks preserve source order and backpressure",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 141,
			column: 3,
			category: "dependent_file_cursor",
			note: "walkDiscoveryDirectory(): sequential file/dir walk follows the discovered source boundary",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 174,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRequestedSkip(): ordered SKIP_RESULT protocol emission",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 308,
			column: 9,
			category: "ordered_protocol_emission",
			note: "processPointRecords(): ordered schema admission and point protocol emission",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 367,
			column: 9,
			category: "ordered_protocol_emission",
			note: "processSegmentRecords(): ordered schema admission and segment protocol emission",
		},
		{
			path: "connectors/google_maps/index.ts",
			line: 536,
			column: 3,
			category: "dependent_file_cursor",
			note: "loadExports(): sequential file progress follows the discovered source order",
		},
		{
			path: "connectors/google_maps_data_portability/index.ts",
			line: 310,
			column: 18,
			category: "dependent_pagination",
			note: "collectResourceGroup(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_messages/index.ts",
			line: 732,
			column: 14,
			category: "dependent_pagination",
			note: "fetchChatMessages(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/google_messages/index.ts",
			line: 877,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 122,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 178,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 229,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 339,
			column: 18,
			category: "dependent_file_cursor",
			note: "buildPhotoRecordForFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/google_takeout/index.ts",
			line: 543,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/groupme/incremental-frontier.test.ts",
			line: 542,
			column: 16,
			category: "test_assertion_sequencing",
			note: "cappedForwardWalk(): deliberately reimplements a page-capped pagination loop to prove the >old-cap discriminator test actually fails under the old (removed) cap — sequential by design, not production code",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 334,
			column: 27,
			category: "dependent_file_cursor",
			note: "reader.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 792,
			column: 4,
			category: "provider_pacing_backpressure",
			note: "normalizeOneAttachment(): rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 958,
			column: 3,
			category: "dependent_pagination",
			note: "fetchPaginatedList(): next request depends on the prior page's page-number cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1460,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "emitInScopeGroupMessages(): toGroupMessageRecord() rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1521,
			column: 3,
			category: "dependent_pagination",
			note: "collectGroupMessagesForwardFromCursor(): next request depends on the prior page's after_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1665,
			column: 3,
			category: "dependent_pagination",
			note: "collectGroupMessagesBackwardToNaturalEnd(): next request depends on the prior page's before_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 1989,
			column: 6,
			category: "ordered_protocol_emission",
			note: 'emitRecord("groups"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2025,
			column: 6,
			category: "ordered_protocol_emission",
			note: 'emitRecord("direct_messages"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2094,
			column: 3,
			category: "dependent_pagination",
			note: "collectDirectChatMessagesForChat(): next request depends on the prior page's before_id cursor; no page-count ceiling, terminates on the natural short/empty page or NonProgressError",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2138,
			column: 19,
			category: "provider_pacing_backpressure",
			note: "toDirectChatMessageRecord(): rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2190,
			column: 24,
			category: "shared_mutable_accumulator",
			note: "collectDirectChatMessages(): loop body mutates a shared considered accumulator the next iteration reads",
		},
		{
			path: "connectors/groupme/index.ts",
			line: 2561,
			column: 25,
			category: "shared_mutable_accumulator",
			note: "collectGroupMessages(): loop body mutates shared considered/nextCursors accumulators the next iteration reads",
		},
		{
			path: "connectors/heb/index.ts",
			line: 320,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 795,
			column: 18,
			category: "dependent_pagination",
			note: "resolveOrderDetail(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/heb/index.ts",
			line: 820,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 868,
			column: 18,
			category: "dependent_pagination",
			note: "recoverPendingOrderItemDetailGapPage(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/heb/index.ts",
			line: 940,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/heb/index.ts",
			line: 1144,
			column: 5,
			category: "dependent_pagination",
			note: "processListOrder(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/ical/index.ts",
			line: 61,
			column: 11,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/ical/index.ts",
			line: 81,
			column: 17,
			category: "ordered_protocol_emission",
			note: "fetchIcs(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ical/index.ts",
			line: 126,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ical/index.ts",
			line: 160,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitEventsFromSource(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/imessage/index.ts",
			line: 370,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/imessage/index.ts",
			line: 417,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/imessage/index.ts",
			line: 694,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "resolveAttachmentHydration(): rate-limited/budget-gated blob-upload call",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 215,
			column: 28,
			category: "dependent_file_cursor",
			note: "readBodyWithStreamingCap(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 879,
			column: 4,
			category: "ordered_protocol_emission",
			note: 'emitRecord("libraries"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 926,
			column: 21,
			category: "dependent_pagination",
			note: "collectItemsForLibrary(): next request depends on the prior page's StartIndex cursor",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 968,
			column: 4,
			category: "ordered_protocol_emission",
			note: 'emitRecord("items"): Collection Profile protocol emission requiring in-order delivery',
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 1008,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "collectItems(): loop body mutates shared state.items/totalItemsEmitted accumulator the next iteration reads",
		},
		{
			path: "connectors/jellyfin/index.ts",
			line: 1084,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitErrorSkipResults(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/netflix_export/index.ts",
			line: 356,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/netflix_export/parsers.ts",
			line: 187,
			column: 26,
			category: "dependent_file_cursor",
			note: "fd.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/notion/index.ts",
			line: 216,
			column: 3,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/notion/index.ts",
			line: 325,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/oura/index.ts",
			line: 300,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/pocket/index.ts",
			line: 182,
			column: 18,
			category: "dependent_pagination",
			note: "fetchPocketPage(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/pocket/index.ts",
			line: 191,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/reddit/index.ts",
			line: 525,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/reddit/index.ts",
			line: 717,
			column: 18,
			category: "dependent_pagination",
			note: "collectStream(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/reddit/integration.test.ts",
			line: 1360,
			column: 3,
			category: "test_assertion_sequencing",
			note: "collectStream(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/reddit/integration.test.ts",
			line: 1423,
			column: 3,
			category: "test_assertion_sequencing",
			note: "collectStream(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/signal/index.ts",
			line: 746,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/signal/index.ts",
			line: 777,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/signal/index.ts",
			line: 793,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/signal/index.ts",
			line: 1049,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/signal/index.ts",
			line: 1127,
			column: 18,
			category: "dependent_pagination",
			note: "resolveAttachmentHydration(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/slack/fail-open.test.ts",
			line: 233,
			column: 31,
			category: "test_assertion_sequencing",
			note: "runStream(): test drives/asserts an ordered per-stream fail-open coverage assertion",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1791,
			column: 18,
			category: "shared_mutable_accumulator",
			note: "refreshScopedArchive(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/slack/index.ts",
			line: 1926,
			column: 5,
			category: "shared_mutable_accumulator",
			note: "runRequestedStreams(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2425,
			column: 6,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2434,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2439,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2737,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 2808,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitWithFingerprint(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3264,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3292,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3304,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3316,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3364,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/slack/index.ts",
			line: 3826,
			column: 28,
			category: "dependent_file_cursor",
			note: "reclaimUploads(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/slack/slack-api.ts",
			line: 298,
			column: 16,
			category: "dependent_pagination",
			note: "slackApiPost(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/slack/slack-api.ts",
			line: 366,
			column: 16,
			category: "dependent_pagination",
			note: "slackApiGet(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/spotify/index.ts",
			line: 316,
			column: 3,
			category: "dependent_pagination",
			note: "paginate(): page progress follows the fetched page before advancing its cursor",
		},
		{
			path: "connectors/spotify/index.ts",
			line: 321,
			column: 18,
			category: "shared_mutable_accumulator",
			note: "paginate(): fold accumulator from each item is the next iteration's input",
		},
		{
			path: "connectors/spotify/index.ts",
			line: 481,
			column: 3,
			category: "ordered_protocol_emission",
			note: "progress(): top-artist time-range windows report in-order before the next window starts",
		},
		{
			path: "connectors/steam/index.ts",
			line: 518,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/strava/index.ts",
			line: 243,
			column: 5,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/twitter_archive/index.ts",
			line: 150,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/credit-card-billing-stats.test.ts",
			line: 256,
			column: 3,
			category: "test_assertion_sequencing",
			note: "deps.emitRecord(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 384,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 544,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 879,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 944,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 988,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emit(): DETAIL_GAP_RECOVERED emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 1437,
			column: 4,
			category: "ordered_browser_interaction",
			note: "page.goto(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2274,
			column: 19,
			category: "bounded_retry_polling",
			note: "runSingleLadderAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2416,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2622,
			column: 3,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 2855,
			column: 4,
			category: "ordered_protocol_emission",
			note: "deps.emit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3101,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3142,
			column: 3,
			category: "ordered_protocol_emission",
			note: "processPdfStatementRow(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3358,
			column: 5,
			category: "ordered_protocol_emission",
			note: "deps.emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3714,
			column: 20,
			category: "ordered_browser_interaction",
			note: "navigateToCardOrGap(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/index.ts",
			line: 3750,
			column: 6,
			category: "ordered_protocol_emission",
			note: "emitCreditCardNavFailureGaps(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/usaa/integration.test.ts",
			line: 1189,
			column: 19,
			category: "test_assertion_sequencing",
			note: "driveExport(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/usaa/statement-pdfs.ts",
			line: 246,
			column: 7,
			category: "ordered_browser_interaction",
			note: "c.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/statement-pdfs.ts",
			line: 274,
			column: 7,
			category: "ordered_browser_interaction",
			note: "c.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/statement-pdfs.ts",
			line: 767,
			column: 4,
			category: "ordered_browser_interaction",
			note: "hydrateOneStatement(): sequential Playwright action against the shared page/context",
		},
		{
			path: "connectors/usaa/transactions-coverage.test.ts",
			line: 225,
			column: 4,
			category: "test_assertion_sequencing",
			note: "deps.emit(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "connectors/venmo/index.ts",
			line: 363,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/venmo/index.ts",
			line: 515,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/whatsapp/chat-identity-reconciliation.test.ts",
			line: 246,
			column: 23,
			category: "test_assertion_sequencing",
			note: "runImport(): test drives/asserts an ordered per-case side effect (each run's STATE cursor is threaded into the next run to prove the per-identityKey alias cap accumulates and plateaus correctly across 25 sequential imports)",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 174,
			column: 5,
			category: "dependent_file_cursor",
			note: "walk(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 831,
			column: 18,
			category: "provider_pacing_backpressure",
			note: "buildAttachmentRecord(): rate-limited/budget-gated blob-upload call (wraps uploadBlob())",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 1276,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitStateForCursor(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/whatsapp/index.ts",
			line: 1355,
			column: 36,
			category: "dependent_file_cursor",
			note: "parseExportFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "connectors/whatsapp/txt-toctou.test.ts",
			line: 48,
			column: 4,
			category: "test_assertion_sequencing",
			note: "waitForBarrier(): test waits for the fixture writer's ordered filesystem barrier",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 277,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): sleep records must preserve source and protocol order",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 282,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitRecord(): workout records must preserve source and protocol order",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 329,
			column: 25,
			category: "provider_pacing_backpressure",
			note: "fetchPath(): bounded WHOOP history windows stay sequential to avoid provider pressure",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 332,
			column: 4,
			category: "ordered_protocol_emission",
			note: "emitAggregateRecord(): records preserve WHOOP window order before cursor state",
		},
		{
			path: "connectors/whoop/index.ts",
			line: 339,
			column: 3,
			category: "ordered_protocol_emission",
			note: "emit(): stream cursor state follows all covered WHOOP records",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1030,
			column: 5,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1279,
			column: 4,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1285,
			column: 5,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1388,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1510,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1644,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1769,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 1886,
			column: 4,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2022,
			column: 3,
			category: "dependent_pagination",
			note: "progress(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2042,
			column: 4,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2184,
			column: 3,
			category: "ordered_protocol_emission",
			note: "trackAndEmit(): Collection Profile protocol emission requiring in-order delivery",
		},
		{
			path: "connectors/ynab/index.ts",
			line: 2486,
			column: 17,
			category: "dependent_pagination",
			note: "collectForBudget(): next request depends on the prior page's cursor/offset/response",
		},
		{
			path: "scripts/run-tests.mjs",
			line: 36,
			column: 2,
			category: "dependent_file_cursor",
			note: "collectTestFiles(): sequential glob() per fixed test-directory pattern; trivial fixed-size loop over 5 patterns, no reason to parallelize",
		},
		{
			path: "src/adaptive-lane.ts",
			line: 495,
			column: 20,
			category: "bounded_retry_polling",
			note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/amazon.ts",
			line: 91,
			column: 13,
			category: "ordered_browser_interaction",
			note: "locator.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/amazon.ts",
			line: 94,
			column: 8,
			category: "ordered_browser_interaction",
			note: "el.isVisible(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/chase.ts",
			line: 236,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 362,
			column: 7,
			category: "bounded_retry_polling",
			note: "checkSession(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 467,
			column: 4,
			category: "ordered_browser_interaction",
			note: "candidate.waitFor(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 679,
			column: 3,
			category: "bounded_retry_polling",
			note: "checkpoint(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/chatgpt.ts",
			line: 1072,
			column: 3,
			category: "bounded_retry_polling",
			note: "page.waitForTimeout(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1782,
			column: 4,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1832,
			column: 4,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1902,
			column: 4,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.test.ts",
			line: 1938,
			column: 14,
			category: "test_assertion_sequencing",
			note: "ensureHebSession(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 177,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 196,
			column: 17,
			category: "ordered_browser_interaction",
			note: "locator.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 199,
			column: 31,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 220,
			column: 17,
			category: "ordered_browser_interaction",
			note: "locator.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 223,
			column: 31,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 300,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 335,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 373,
			column: 36,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 476,
			column: 9,
			category: "bounded_retry_polling",
			note: "hasDismissibleInterstitial(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 739,
			column: 19,
			category: "ordered_browser_interaction",
			note: "inspectPostSubmitAuthSurface(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 947,
			column: 18,
			category: "ordered_browser_interaction",
			note: "fillWhenUsable(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 969,
			column: 37,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/heb.ts",
			line: 1267,
			column: 20,
			category: "bounded_retry_polling",
			note: "waitForUniqueVerificationCodeFormRoot(): retry/poll until the remounted OTP surface is uniquely actionable",
		},
		{
			path: "src/auto-login/manual-action-copy.test.ts",
			line: 48,
			column: 15,
			category: "test_assertion_sequencing",
			note: "readFile(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/auto-login/reddit.test.ts",
			line: 176,
			column: 5,
			category: "bounded_retry_polling",
			note: "makeLocator().waitFor(): bounded test double polling until the simulated locator attaches",
		},
		{
			path: "src/auto-login/reddit.ts",
			line: 420,
			column: 7,
			category: "bounded_retry_polling",
			note: "isSessionLiveWithRetry(): bounded post-manual-handoff re-probe — don't trust a single isSessionLive check right after the owner's continue click",
		},
		{
			path: "src/auto-login/reddit.ts",
			line: 629,
			column: 4,
			category: "ordered_protocol_emission",
			note: "drainProbeTimeouts(): probe-timeout checkpoints must reach the runtime watchdog in the order they were observed",
		},
		{
			path: "src/auto-login/reddit.ts",
			line: 755,
			column: 5,
			category: "bounded_retry_polling",
			note: "hasSessionCookie(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/usaa.ts",
			line: 190,
			column: 17,
			category: "ordered_browser_interaction",
			note: "action.count(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/usaa.ts",
			line: 195,
			column: 14,
			category: "ordered_browser_interaction",
			note: "locator.isVisible(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/usaa.ts",
			line: 377,
			column: 16,
			category: "bounded_retry_polling",
			note: "requestOtp(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/auto-login/venmo.test.ts",
			line: 1008,
			column: 6,
			category: "bounded_retry_polling",
			note: "makeTwoStepVenmoPage(): fake Locator.waitFor() polls its own deadline, mirroring Playwright's real wait semantics",
		},
		{
			path: "src/auto-login/venmo.test.ts",
			line: 1921,
			column: 5,
			category: "test_assertion_sequencing",
			note: "ensureVenmoSession(): test drives an ordered retry-if-retryable dispatch simulation",
		},
		{
			path: "src/auto-login/venmo.test.ts",
			line: 2711,
			column: 6,
			category: "bounded_retry_polling",
			note: "makeBlankHandoffPage(): fake Locator.waitFor() polls its own deadline, mirroring Playwright's real wait semantics",
		},
		{
			path: "src/auto-login/venmo.ts",
			line: 719,
			column: 30,
			category: "ordered_browser_interaction",
			note: "Promise.all(): sequential Playwright action against the shared page/context",
		},
		{
			path: "src/auto-login/venmo.ts",
			line: 767,
			column: 7,
			category: "ordered_browser_interaction",
			note: "clickVenmoLoginSubmit(): submit-control candidates tried in priority order; must stop at the first visible one, since clicking a second control would submit the form twice",
		},
		{
			path: "src/browser-launch.ts",
			line: 703,
			column: 11,
			category: "bounded_retry_polling",
			note: "runAttempt(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/browser-launch.ts",
			line: 1498,
			column: 21,
			category: "dependent_file_cursor",
			note: "readFile(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/browser-launch.ts",
			line: 1608,
			column: 14,
			category: "shared_mutable_accumulator",
			note: "closeRemoteDevToolsTarget(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/browser-launch.ts",
			line: 1621,
			column: 25,
			category: "shared_mutable_accumulator",
			note: "fetchRemoteDevToolsTargets(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/collector-registry.test.ts",
			line: 72,
			column: 31,
			category: "test_assertion_sequencing",
			note: "readFile(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/collector-registry.test.ts",
			line: 91,
			column: 31,
			category: "test_assertion_sequencing",
			note: "readFile(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-http-governor.test.ts",
			line: 330,
			column: 3,
			category: "test_assertion_sequencing",
			note: "g.request(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-http-governor.test.ts",
			line: 359,
			column: 3,
			category: "test_assertion_sequencing",
			note: "g.request(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-http-governor.test.ts",
			line: 423,
			column: 3,
			category: "test_assertion_sequencing",
			note: "g1.request(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-runtime-session-watchdog.test.ts",
			line: 159,
			column: 4,
			category: "test_assertion_sequencing",
			note: "watchdog.checkpoint(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/connector-runtime.ts",
			line: 1683,
			column: 7,
			category: "shared_mutable_accumulator",
			note: "closeBrowserPage(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/interaction-handler.ts",
			line: 87,
			column: 4,
			category: "dependent_file_cursor",
			note: "access(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/interaction-handler.ts",
			line: 126,
			column: 18,
			category: "bounded_retry_polling",
			note: "promptStdin(): retry/backoff/poll loop gated on the prior attempt's outcome",
		},
		{
			path: "src/local-device-runtime.ts",
			line: 307,
			column: 3,
			category: "shared_mutable_accumulator",
			note: "queue.enqueue(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/local-device-runtime.ts",
			line: 397,
			column: 16,
			category: "shared_mutable_accumulator",
			note: "input.queue.dequeueReady(): loop body mutates a shared accumulator the next iteration reads",
		},
		{
			path: "src/local-jsonl-cursor.ts",
			line: 107,
			column: 25,
			category: "dependent_file_cursor",
			note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/local-jsonl-cursor.ts",
			line: 243,
			column: 26,
			category: "dependent_file_cursor",
			note: "handle.read(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/local-jsonl-cursor.ts",
			line: 262,
			column: 5,
			category: "dependent_file_cursor",
			note: "onLine(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/page-ceiling.ts",
			line: 22,
			column: 24,
			category: "dependent_pagination",
			note: "walkPagesWithCeiling(): args.fetchPage(): next page's fetch decides whether to continue; shared helper now used by venmo, google_calendar, reddit, heb, and google_contacts pagination loops that previously carried their own dependent_pagination allowlist rows",
		},
		{
			path: "src/profile-lock.ts",
			line: 141,
			column: 4,
			category: "dependent_file_cursor",
			note: "fs.unlink(): sequential file/dir walk, incremental byte-offset read, or one-way fs mutation",
		},
		{
			path: "src/reference-blob-uploader.test.ts",
			line: 47,
			column: 11,
			category: "test_assertion_sequencing",
			note: "reader.read(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/reference-blob-uploader.test.ts",
			line: 118,
			column: 3,
			category: "test_assertion_sequencing",
			note: "assert.rejects(): test drives/asserts an ordered per-case side effect",
		},
		{
			path: "src/scheduler-runner.ts",
			line: 287,
			column: 4,
			category: "devtool_sequential_output",
			note: "registerManifest(): manual dev-tool script printing ordered per-item console output",
		},
		{
			path: "src/test-fixtures/scenario-cli-multi-stream-stub-connector.ts",
			line: 62,
			column: 4,
			category: "ordered_protocol_emission",
			note: "collect(): per-stream PROGRESS line must precede that stream's own fetch and RECORD/STATE emissions",
		},
		{
			path: "src/test-fixtures/scenario-cli-multi-stream-stub-connector.ts",
			line: 77,
			column: 5,
			category: "ordered_protocol_emission",
			note: "collect(): stub items are emitted as RECORDs in fetched-page order so the captured fixture's expected.records order is deterministic",
		},
		{
			path: "src/test-fixtures/scenario-cli-stub-connector.ts",
			line: 89,
			column: 16,
			category: "dependent_pagination",
			note: "collect(): next page's fetch depends on the prior page's next_cursor value",
		},
		{
			path: "src/test-fixtures/scenario-cli-stub-connector.ts",
			line: 97,
			column: 5,
			category: "ordered_protocol_emission",
			note: "collect(): stub items are emitted as RECORDs in fetched-page order so the captured fixture's expected.records order is deterministic",
		},
		{
			path: "src/test-fixtures/scenario-fidelity-http-connector.ts",
			line: 63,
			column: 4,
			category: "ordered_protocol_emission",
			note: "collect(): page items are emitted as RECORDs in fetched-response order, matching the fidelity fixture's numbered request sequence",
		},
		{
			path: "src/test-fixtures/scenario-record-har-stub-connector.ts",
			line: 181,
			column: 5,
			category: "ordered_protocol_emission",
			note: "collect(): stub items are emitted as RECORDs in fetched-response order, mirroring scenario-cli-stub-connector.ts's identical loop",
		},
		{
			path: "src/test-fixtures/scenario-watchdog-paced-connector.ts",
			line: 65,
			column: 4,
			category: "ordered_protocol_emission",
			note: "collect(): each record's pacing sleep must complete before that record's own RECORD emission so the watchdog-window proof observes real inter-record gaps, not a burst",
		},
	];
